# -*- coding: utf-8 -*-
from pathlib import Path
path = Path("src/App.tsx")
text = path.read_text(encoding="utf-8")
old = "      <CTASection onGetStarted={handleGetStarted} />\n\n      <footer className=\"bg-gradient-to-br from-gray-800 via-gray-900 to-indigo-950 dark:bg-gradient-to-br dark:from-gray-900 dark:via-gray-950 dark:to-black text-white py-12\">\n        <div className=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\n          <div className=\"grid md:grid-cols-4 gap-8\">\n            <div>\n              <h3 className=\"text-lg font-semibold mb-4\">BaşarıYolu</h3>\n              <p className=\"text-gray-400 text-sm\">\n                Türkiye\'nin en kapsamlı öğrenci takip platformu.\n                Yapay zeka desteğiyle akademik başarınızı artırın.\n              </p>\n            </div>\n            <div>\n              <h4 className=\"font-semibold mb-3\">Özellikler</h4>\n              <ul className=\"space-y-2 text-sm text-gray-400\">\n                <li>Deneme Takibi</li>\n                <li>AI Analiz</li>\n                <li>Veli Paneli</li>\n                <li>Ödev Sistemi</li>\n              </ul>\n            </div>\n            <div>\n              <h4 className=\"font-semibold mb-3\">İçerik</h4>\n              <ul className=\"space-y-2 text-sm text-gray-400\">\n                <li>\n                  <button onClick={handleNavigateToBlog} className=\"hover:text-white\">\n                    Blog\n                  </button>\n                </li>\n                <li>Çalışma Teknikleri</li>\n                <li>Motivasyon</li>\n              </ul>\n            </div>\n            <div>\n              <h4 className=\"font-semibold mb-3\">İletişim</h4>\n              <p className=\"text-sm text-gray-400\">destek@basariyolum.com</p>\n              <p className=\"text-sm text-gray-400\">+90 850 000 00 00</p>\n            </div>\n          </div>\n        </div>\n      </footer>"
new = "      <CTASection onGetStarted={handleGetStarted} />\n      <SiteFooter\n        onNavigateToBlog={handleNavigateToBlog}\n        onNavigateToTerms={handleNavigateToTerms}\n        onNavigateToPrivacy={handleNavigateToPrivacy}\n        onNavigateToRefund={handleNavigateToRefund}\n      />"
if old not in text:
    raise SystemExit('old block not found')
path.write_text(text.replace(old, new), encoding="utf-8")
